#!/bin/sh

[".zsh/pure"]
type = "git-repo"
url = "https://github.com/sindresorhus/pure.git"
refreshPeriod = "168h"

[".config/nvim/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "168h"
